### ISSUE TITLE
Definição de framework

### ISSUE THREAD

**Issue by alcalcides** [phbomfim/mat63-key-system#1]

**Comment by alcalcides** [comment]
Sobre o front end, posso sugerir reactjs/next ou html raiz com JS puro mesmo, JS vanilla

**Comment by phbomfim** [comment]
No frontend definimos por utilizar:

- HTML 5 
- CSS puro
- JS puro

**Comment by phbomfim** [comment]
No backend ficou definido a linguagem Python. Talvez usemos o Django para facilitar no desenvolvimento web.

Para banco de dados, utilizaremos MySQL.
